app/urls.py
from django.urls import path
from . import views

urlpatterns = [
path('', views.home, name='home'),
path('user/<int:pk>', views.UserDetail.as_view(), name='user'),
path('kor', views.update_profile, name='kor'),
path('osati/unos', views.OsatiCreate.as_view(), name='osati-unos'),
path('osati', views.PregledOSati.as_view(), name='osati-pregled'),
path('osati1', views.KrajVremena.as_view(), name='krajvremena'),
path("register/", views.register, name="register"),
path('registered/', views.home, name='registered'),
path('osati/<int:pk>/update', views.OSatiUpdate.as_view(), name='osati-update'),
path('zadaci/unos', views.ListaZCreate.as_view(), name='zadaci-unos'),
path('zadaci', views.PregledZ.as_view(), name='zadaci-pregled'),
path('zadacir', views.PregledZR.as_view(), name='zadacir-pregled'),
path('zadaci/<int:pk>/update', views.ZadaciUpdate.as_view(), name='zadaci-update'),
path('zadaci/<int:pk>',views.ZDetail.as_view(), name='zadatak-detail'),
path('zadacib/<int:pk>',views.ZadatakDelete.as_view(), name='zadatak-del'),
]

projekt2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime
from django.dispatch import receiver
from django.db.models.signals import post_save 

class OdradjeniSati(models.Model):
	datum = models.DateField(null= True, blank = True, auto_now_add=True)
	pvremena = models. TimeField(null= True, blank = True, verbose_name= 'Početak radnog vremena')
	kvremena = models. TimeField(null= True, blank = True, verbose_name= 'Kraj radnog vremena')
	korisnik = models.ForeignKey(User, on_delete=models.CASCADE ,null = True, blank = True,verbose_name = 'Korisnik' )
	
	class Meta:
		verbose_name_plural = "Odrađeni sati"

	def __int__(self):
		return self.id

	def razlika(self):
		date_format = "%H:%M:%S"
		if self.pvremena != None and self.kvremena != None:
			time1 = datetime.strptime(str(self.pvremena), date_format)
			time2 = datetime.strptime(str(self.kvremena), date_format)
			difference = time2-time1
			diffe = difference.seconds / (60*60)
			diff = str(round(diffe,2))
			return diff

	def vrijeme(self):
		date_format = "%H:%M:%S"
		if self.pvremena != None and self.kvremena != None:
			time1 = datetime.strptime(str(self.pvremena), date_format)
			dtime1 = datetime.strptime('03:00:00', '%H:%M:%S')
			dtime2 = datetime.strptime('16:00:00', '%H:%M:%S')
			dtime3 = datetime.strptime('16:00:00', '%H:%M:%S')
			dtime5 = datetime.strptime('00:00:00', '%H:%M:%S')
			if time1 >= dtime1 and time1 <= dtime2: 
				tip = 'Redovna dnevna smjena'
				return tip
			elif time1 >= dtime3 or time1 >= dtime5 and time1 <= dtime2:
				tip = 'Noćna smjena'
				return tip

	def prekovremeni(self):
		date_format = "%H:%M:%S"
		if self.pvremena != None and self.kvremena != None:
			time1 = datetime.strptime(str(self.pvremena), date_format)
			time2 = datetime.strptime(str(self.kvremena), date_format)
			difference = time2-time1
			diffe = difference.seconds / (60*60)
			
			if diffe > 8:
				diffe1 = diffe - 8
				diff2 = str(round(diffe1,2))
				prk = 'Da'
				return prk, diff2
			else: 
				prk = 'Ne'
				return prk

	def get_absolute_url(self):
		return reverse('osati-pregled')

class ListaZadataka(models.Model):
	naziv = models.CharField(max_length=100)
	opis = models.TextField(max_length = 600)
	korisnik = models.ForeignKey(User, on_delete=models.CASCADE ,null = True, blank = True,verbose_name = 'Korisnik' )
	STATUS = (
		('u', 'U Tijeku'),
		('r', 'Riješeno'),)
	status = models.CharField(max_length=1,choices=STATUS,blank=True,default='u',)
	class Meta:
		verbose_name_plural = "Kreirani zadaci"

	def __str__(self):
		return self.naziv

	def get_absolute_url(self):
		return reverse('zadatak-detail', args=[str(self.id)])

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nazivfirme = models.CharField(max_length=500, blank=True, verbose_name= 'Naziv firme')
    adresa = models.CharField(max_length=30, blank=True)
    kontakt = models.CharField(max_length= 10 , blank=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
    	if created:
    		Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
    	instance.profile.save()

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/main.css' %}">

    {% if title %}
        <title>Aplikacija za evidenciju radnih sati i zadataka {{ title }}</title>
    {% else %}
        <title>Aplikacija za evidenciju radnih sati i zadataka </title>
    {% endif %}
</head>
<!DOCTYPE html>
<html>
<head>
<style>
body {
  background-color: #FFFFE0;
}
</style>
</head>
</html>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'home' %}">Aplikacija za evidenciju radnih sati i zadataka </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{%url 'osati-unos'%}">Unos početka radnog vremena</a>
          <a class="dropdown-item" href="{%url 'krajvremena' %}">Unos kraja radnog vremena</a>
          <a class="dropdown-item" href="{%url 'zadaci-unos' %}">Unos novog zadatka</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{%url 'osati-pregled'%}">Pregled mojih sati</a>
          <a class="dropdown-item" href="{%url 'zadaci-pregled'%}">Pregled mojih zadataka</a>
          <a class="dropdown-item" href="{%url 'zadacir-pregled'%}">Pregled mojih riješenih zadataka</a>
        </div>
      </li>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
               {% if user.is_authenticated %}
                <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{%url 'user' user.id%}">Profil</a>
                  {%if user.is_superuser%}
                  <a class="dropdown-item" href="/admin">Admin</a>
                  {%endif%}
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'logout'%}?next={{request.path}}">Odjava</a>
                </div>
              </li>
              {% else %}
                   <a class="nav-item nav-link" href="{% url 'login'%}?next={{request.path}}">Prijava</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div id= "mydiv" class="col-md-12">
          {% block content %}{% endblock %}
        </div>
        
              </ul>
            </p>
          </div>
      </div>
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
   <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <script>
        $('#id_datum').datepicker({format: 'dd.mm.yyyy'});
    </script>
    <script>
        $('#id_pvremena').timepicker();
    </script>
    <script>
        $('#id_kvremena').timepicker();
    </script>
</body>
</html>

app/templates/app/baselogin.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'app/main.css' %}">
<!DOCTYPE html>
<html>
<head>
<style>
body {
  background-color: #FFFFE0;
}
</style>
</head>
</html>

    {% if title %}
        <title>Aplikacija za evidenciju radnih sati i zadataka{{ title }}</title>
    {% else %}
        <title>Aplikacija za evidenciju radnih sati i zadataka</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'home' %}">Aplikacija za evidenciju radnih sati i zadataka</a>
  </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
            </div>
            <div class="navbar-nav">
                  <a class="nav-item nav-link" href="{% url 'register'%}">Registracija</a> 
          </div>
        </div>
      </nav>
    </header>
<html>
<head>
<style>
h4 {text-align: center;}
</style>
</head>
<body>

<h4>Unesite korisničko ime i lozinku !</h4>

</body>
</html>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% block content %}{% endblock %}
        </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
   <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

app/templates/app/home.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<meta http-equiv="refresh" content="600" />
<style>
body {
    background-color: #FFFFE0;
}
div {
    text-align:center;
}
</style>

<div id="clockbox"></div>

<script type="text/javascript">
var tday=["Ned","Pon","Uto","Sri","Čet","Pet","Sub"];
var tmonth=["Sij","Velj","Ožu","Tra","Svi","Lip","Srp","Kol","Ruj","Lis","Stu","Pro"];

function GetClock(){
var d=new Date();
var nday=d.getDay(),nmonth=d.getMonth(),ndate=d.getDate(),nyear=d.getFullYear();
var nhour=d.getHours(),nmin=d.getMinutes(),nsec=d.getSeconds(),ap;

if(nhour==0){ap=" AM";nhour=12;}
else if(nhour<12){ap=" AM";}
else if(nhour==12){ap=" PM";}
else if(nhour>12){ap=" PM";nhour-=12;}

if(nmin<=9) nmin="0"+nmin;
<!-- ## if(nsec<=9) nsec="0"+nsec; -->

var clocktext="<span style=\"font:97pt Arial; color:#4682B4;\">"+nhour+":"+nmin+""+ap+"</span> <br> <span style=\"font:14pt Arial; color:#00000 ;\">"+tday[nday]+", "+ndate+" "+tmonth[nmonth]+", "+nyear+"</span>";

document.getElementById('clockbox').innerHTML=clocktext;
}

GetClock();
setInterval(GetClock,1000);
</script>

<a class="weatherwidget-io" href="https://forecast7.com/hr/45d3314d44/rijeka/" data-label_1="RIJEKA" data-label_2="WEATHER" data-icons="Climacons Animated" data-theme="original" >RIJEKA WEATHER</a>
<script>
!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='https://weatherwidget.io/js/widget.min.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','weatherwidget-io-js');
</script>

{%endblock content%}

app/templates/app/listazadataka_confirm_delete.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<h1>Želite li izbrisati?</h1>

<form action="" method="POST">
  {% csrf_token %}
  {{ form|crispy }}
  <div class="input-group mb-3">
  <div class="input-group-append">
    <button type="submit" class="btn btn-danger">Da</button>
</div>
</div>

{% endblock %} 

app/templates/app/listazadataka_form.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <div class="input-group mb-3">
  <div class="input-group-append">
    <button type="submit" class="btn btn-success">Potvrdi</button>
</div>
</div>
  </form>

{% endblock %}

app/templates/app/mojiosati.html
{% extends "app/base.html" %}

{% load crispy_forms_tags %}
{% block content %}

<div class="input-group mb-3">
<div >
<p>Pretraživanje po datumu: </p>
  <form class = " form-row align-items-center" method ="GET" style="padding-bottom: 40px;">
<button type ="submit" id="mybutton" class = "btn btn-primary">Filtriraj</button>
{{filter.form|crispy}}
</form>
</div>
</div>
<div style="padding-top: 20px;">
  <h4>Lista odrađenih sati</h4>
  {% if odradjenisati_list %}
    <table class="table table-bordered">
       <thead class="thead-dark">
        <tr>
      <th scope="col">Datum</th>
      <th scope="col">Početak vremena</th>
      <th scope="col">Kraj vremena</th>
      <th scope="col">Odrađeni sati</th>
      <th scope="col">Tip odrađene smjene</th>
      <th scope="col">Prekovremeni rad</th>
      {%endif%}
        </tr>
      </thead>
  {% for odradjenisati in filter.qs %}
   <tbody>
      <td>{{odradjenisati.datum}}</td>
      <td>{{odradjenisati.pvremena}}</td> 
      <td>{{odradjenisati.kvremena}}</td>   
      <td>{{odradjenisati.razlika}} h</td>
      <td>{{odradjenisati.vrijeme}}</td>
      <td>{{odradjenisati.prekovremeni}}</td>
      </tbody>
      {% endfor %}
      </table>
</div>

{% endblock %}

app/templates/app/mojiosati1.html
{% extends "app/base.html" %}

{% load crispy_forms_tags %}
{% block content %}

<div style="padding-top: 20px;">
  <h4>Lista odrađenih sati</h4>
  <p>Ažurirajte kako bi ste unijeli kraj radnog vremena ! </p>
  {% if odradjenisati_list %}
    <table class="table table-bordered">
       <thead class="thead-dark">
        <tr>
      <th scope="col">Datum</th>
      <th scope="col">Početak vremena</th>
      <th scope="col">Kraj vremena</th>
      <th scope="col"></th>
      {%endif%}
        </tr>
      </thead>
  {% for odradjenisati in odradjenisati_list %}
   <tbody>
      <td>{{odradjenisati.datum}}</td>
      <td>{{odradjenisati.pvremena}}</td> 
      <td>{{odradjenisati.kvremena}}</td>  
      <td><a href="{% url 'osati-update' odradjenisati.id %}">Ažuriraj</a></td> 
      </tbody>
      {% endfor %}
      </table>
</div>

{% endblock %}

app/templates/app/mojizadaci.html
{% extends "app/base.html" %}

{% load crispy_forms_tags %}
{% block content %}

<div style="padding-top: 20px;">
  <h4>Lista mojih zadataka</h4>
  {% if listazadataka_list %}
    <table class="table table-bordered">
       <thead class="thead-dark">
        <tr>
      <th scope="col">Naziv</th>
      <th scope="col">Status</th>
      <th scope="col">Izmjena</th>
      <th scope="col">Brisanje</th>
      {%endif%}
        </tr>
      </thead>
  {% for z in listazadataka_list %}
   <tbody>
      <td><a href="{{z.get_absolute_url}}">{{z.naziv}}</a></td>
      <td>{{z.get_status_display}}</td>  
      <td><a href="{% url 'zadaci-update' z.id %}">Ažuriraj</a></td>
      <td><a href="{% url 'zadatak-del' z.id %}">Izbriši</a></td>  
      </tbody>
      {% endfor %}
      </table>
</div>

{% endblock %}

app/templates/app/mojizadacir.html
{% extends "app/base.html" %}

{% load crispy_forms_tags %}
{% block content %}

<div style="padding-top: 20px;">
  <h4>Lista mojih riješenih zadataka</h4>
  {% if listazadataka_list %}
    <table class="table table-bordered">
       <thead class="thead-dark">
        <tr>
      <th scope="col">Naziv</th>
      <th scope="col">Status</th>
      {%endif%}
        </tr>
      </thead>
  {% for z in listazadataka_list %}
   <tbody>
      <td>{{z.naziv}}</td>
      <td>{{z.get_status_display}}</td>  
      </tbody>
      {% endfor %}
      </table>
</div>

{% endblock %}

app/templates/app/odradjenisati_form.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <div class="input-group mb-3">
  <div class="input-group-append">
    
    <button type="submit" class="btn btn-success">Potvrdi</button>
</div>
</div>
  </form>

{% endblock %}

app/templates/app/profile.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}
{%block content%}

<form method="post">
  {% csrf_token %}
  {{ user_form|crispy}}
  {{ profile_form|crispy }}
  <button class ='button btn-success'type="submit">Spremi</button>
</form>

{%endblock%}

app/templates/app/user_detail.html
{% extends "app/base.html" %}

{% block content %}

<h1>Korisnik: {{ user.get_username }}</h1>

<div style="margin-left:20px;margin-top:20px">

<p><strong>Email:</strong> {{ user.email }}</p>
<p><strong>Ime:</strong> {{ user.first_name }}</p>
<p><strong>Prezime:</strong> {{ user.last_name }}</p>
<p><strong>Naziv firme:</strong> {{ user.profile.nazivfirme }}</p>
<p><strong>Adresa:</strong> {{ user.profile.adresa }}</p>
<p><strong>Kontakt:</strong> {{ user.profile.kontakt }}</p>
</div>

<div>
	<a class="button1 btn-primary" href="{%url 'kor'%}">Ažuriraj podatke</a>
</div>

{% endblock %}

app/templates/app/zadaci_detail.html
{% extends "app/base.html" %}

{% block content %}

<h1>Zadatak: {{ listazadataka.naziv }} </h1>
<p>Opis zadatka: {{listazadataka.opis}}</p>
<ul>
<span class="badge badge-primary badge-pill">{{listazadataka.get_status_display}}</span>
 </ul> 

{% endblock %}